### ISSUE TITLE
[Anon] Bug report: Survivor.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/last-days-zombie-apocalypse#3] opened 2020-03-26 02:36 UTC
**File:** Survivor.catz

**BattleScribe version:** 2.03.19

**Platform:** Android

**Dropbox:** No

**Description:** Outdoorsman is wrong.

1. Melee weapons appears twice.
2. Ranged trained weapons does not appear.

Thank you!

**Comment by mattcaron** [comment] 2020-03-26 13:28
This is actually my bug, but I did it through the form, so it didn't get assigned to me.

I hadn't realized that they'd modernized the infrastructure to do what I had been doing years ago. Lol.

If I have a chance, I'll fix it this weekend. I think I know what's wrong - my guess is a copy and paste for a linked weapons group into outdoorsman and then didn't change it to use Ranged Trained Weapons.

**Comment by andreanespeca** [comment] 2020-03-26 13:51
Hi both!
Matt are you sure this is your fault? have you been working on my datafile for last days zombie apocalypse? anyway don't worry i have updated and fixed as noted. I will release it now so you should be able to get the update tomorrow, hopefully no other bug around. Tbf not playing since quite a while so don't remember all the rules

**Comment by mattcaron** [comment] 2020-03-26 14:28
Sorry, I was unclear - it's my bug *report*, not a bug I caused. I haven't touched the files at all.

And, if you've fixed it, thanks so much for your prompt attention.

**Comment by andreanespeca** [comment] 2020-03-26 14:32
Aw right now i see you have implemented a new bug report, that's great! thanks for letting me know

**Closed as completed** 2020-04-29 14:19 UTC
